spring.datasource.url=jdbc:postgresql://terraform-20260516081813380700000001.c94ccscesisj.ap-south-1.rds.amazonaws.com:5432/flashsale

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

spring.data.redis.ssl.enabled=true

server.port=8080
