spring.application.name=flash-sale-order-system
spring.datasource.url=jdbc:postgresql://postgres:5432/flashsale_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=6000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/flash-sale
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/flash-sale/protocol/openid-connect/certs
keycloak.server-url=http://keycloak:8080
keycloak.realm=master
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin
server.port=8000
