spring.datasource.url=jdbc:postgresql://terraform-20260516081813380700000001.c94ccscesisj.ap-south-1.rds.amazonaws.com:5432/flashsale

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.kafka.bootstrap-servers=kafka:9092

spring.data.redis.host=172.31.25.100
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true

spring.data.redis.lettuce.extension.ssl.disable-peer-verification=true

spring.data.redis.connect-timeout=30000
spring.data.redis.timeout=30s

server.port=8080

management.tracing.enabled=false