spring.datasource.url=jdbc:postgresql://terraform-20260516081813380700000001.c94ccscesisj.ap-south-1.rds.amazonaws.com:5432/flashsale

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.kafka.bootstrap-servers=kafka:9092

spring.data.redis.host=flash-sale-redis.dlejyv.0001.aps1.cache.amazonaws.com
spring.data.redis.port=6379

server.port=8080

management.tracing.enabled=false