ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE products
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE flash_sales
ALTER COLUMN start_time TYPE TIMESTAMP WITH TIME ZONE
USING start_time AT TIME ZONE 'UTC';

ALTER TABLE flash_sales
ALTER COLUMN end_time TYPE TIMESTAMP WITH TIME ZONE
USING end_time AT TIME ZONE 'UTC';

ALTER TABLE flash_sales
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE orders
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';